import React,{useState,useEffect}from'react';import{Search,Plus,Edit3,Trash2,Phone,Mail,Calendar}from'lucide-react';

export default function Leads({T,theme:t}){const[leads,setLeads]=useState([]);const[l,setL]=useState(true);const[s,setS]=useState('');const[sf,setSf]=useState('');const[sh,setSh]=useState(false);const[eid,setEid]=useState(null);const[f,setF]=useState({name:'',phone:'',email:'',interest:'',score:50,status:'new',notes:'',follow_up_date:''});
const fl=async()=>{setL(true);try{const p=new URLSearchParams();if(sf)p.set('status',sf);if(s)p.set('search',s);const r=await fetch('/api/leads?'+p);const d=await r.json();setLeads(Array.isArray(d.leads)?d.leads:[])}catch(e){console.error(e)}setL(false)};
useEffect(()=>{fl()},[sf]);
const on=()=>{setEid(null);setF({name:'',phone:'',email:'',interest:'',score:50,status:'new',notes:'',follow_up_date:''});setSh(true)};
const oe=l=>{setEid(l.id);setF({name:l.name,phone:l.phone,email:l.email||'',interest:l.interest||'',score:l.score,status:l.status,notes:l.notes||'',follow_up_date:l.follow_up_date?l.follow_up_date.split('T')[0]:''});setSh(true)};
const sv=async()=>{if(!f.name||!f.phone)return;try{await fetch(eid?`/api/leads/${eid}`:'/api/leads',{method:eid?'PATCH':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(f)});fl();setSh(false)}catch(e){console.error(e)}};
const dl=async(id)=>{if(!confirm('Delete?'))return;try{await fetch(`/api/leads/${id}`,{method:'DELETE'});fl()}catch(e){console.error(e)}};
const BD=c=>({display:'inline-flex',padding:'2px 10px',borderRadius:20,fontSize:11,fontWeight:500,background:`${c}18`,border:`1px solid ${c}30`,color:c});
const sc2=s=>s>=90?t.teal:s>=70?t.blue:s>=50?t.amber:t.red;
const IS={width:'100%',background:t.inputBg,border:`1px solid ${t.inputBorder}`,borderRadius:10,padding:'9px 14px',color:t.text,fontSize:13,outline:'none',boxSizing:'border-box'};

return(<div style={{display:'flex',flexDirection:'column',gap:20}}>
<div style={{display:'flex',justifyContent:'space-between',alignItems:'center',flexWrap:'wrap',gap:12}}><div><h2 style={{fontSize:24,fontWeight:700,color:t.text,margin:0}}>{T('leads')}</h2><div style={{fontSize:13,color:t.textMuted,marginTop:4}}>{leads.length} leads·{leads.filter(l=>l.status==='qualified').length} qualified</div></div>
<button onClick={on}style={{display:'flex',alignItems:'center',gap:6,padding:'9px 18px',borderRadius:10,border:'none',cursor:'pointer',background:'linear-gradient(135deg,#10b981,#059669)',color:'#fff',fontSize:13,fontWeight:600,boxShadow:'0 3px 15px rgba(16,185,129,.25)'}}><Plus size={15}/>{T('newLead')}</button></div>

{sh&&<div style={{position:'fixed',inset:0,zIndex:100,display:'flex',alignItems:'center',justifyContent:'center',background:t.overlay,backdropFilter:'blur(4px)'}}onClick={()=>setSh(false)}><div style={{background:t.surface,border:`1px solid ${t.border}`,borderRadius:16,padding:24,width:'90%',maxWidth:440,maxHeight:'90vh',overflow:'auto',boxShadow:t.shadowMd}}onClick={e=>e.stopPropagation()}><h3 style={{fontSize:18,fontWeight:700,color:t.text,margin:'0 0 16px 0'}}>{eid?T('editLead'):T('newLead')}</h3><div style={{display:'flex',flexDirection:'column',gap:10}}><input placeholder={T('callerName')}value={f.name}onChange={e=>setF(p=>({...p,name:e.target.value}))}style={IS}/><input placeholder={T('callerNumber')}value={f.phone}onChange={e=>setF(p=>({...p,phone:e.target.value}))}style={IS}/><input placeholder="Email"value={f.email}onChange={e=>setF(p=>({...p,email:e.target.value}))}style={IS}/><input placeholder={T('interest')}value={f.interest}onChange={e=>setF(p=>({...p,interest:e.target.value}))}style={IS}/><div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:10}}><input type="number"min={0}max={100}placeholder={T('score')}value={f.score}onChange={e=>setF(p=>({...p,score:parseInt(e.target.value)||0}))}style={IS}/><select value={f.status}onChange={e=>setF(p=>({...p,status:e.target.value}))}style={IS}><option value="new">{T('new')}</option><option value="contacted">{T('contacted')}</option><option value="qualified">{T('qualified')}</option><option value="lost">{T('lost')}</option></select></div><textarea placeholder={T('notes')}value={f.notes}onChange={e=>setF(p=>({...p,notes:e.target.value}))}rows={2}style={{...IS,resize:'vertical'}}/><input type="date"value={f.follow_up_date}onChange={e=>setF(p=>({...p,follow_up_date:e.target.value}))}style={IS}/><div style={{display:'flex',gap:10,marginTop:4}}><button onClick={sv}style={{flex:1,padding:10,borderRadius:10,border:'none',cursor:'pointer',background:'linear-gradient(135deg,#10b981,#059669)',color:'#fff',fontSize:13,fontWeight:600}}>{T('save')}</button><button onClick={()=>setSh(false)}style={{flex:1,padding:10,background:'transparent',border:'none',color:t.textMuted,fontSize:13,cursor:'pointer'}}>{T('cancel')}</button></div></div></div></div>}

<div style={{display:'flex',gap:10,flexWrap:'wrap'}}><div style={{position:'relative',flex:1,minWidth:220}}><Search size={15}color={t.textMuted}style={{position:'absolute',left:12,top:'50%',transform:'translateY(-50%)'}}/><input value={s}onChange={e=>setS(e.target.value)}onKeyDown={e=>e.key==='Enter'&&fl()}placeholder={T('leadSearchPlaceholder')}style={{...IS,paddingLeft:36}}/></div><select value={sf}onChange={e=>setSf(e.target.value)}style={{...IS,width:'auto',minWidth:140}}><option value="">{T('all')}</option><option value="new">{T('new')}</option><option value="contacted">{T('contacted')}</option><option value="qualified">{T('qualified')}</option><option value="lost">{T('lost')}</option></select></div>

{l?<div style={{display:'flex',justifyContent:'center',padding:48}}><div style={{width:28,height:28,border:`2px solid ${t.pink}`,borderTopColor:'transparent',borderRadius:'50%',animation:'spin .7s linear infinite'}}/></div>:leads.length===0?<div style={{textAlign:'center',padding:48,color:t.textMuted}}><div style={{fontSize:40,marginBottom:12}}>&#x1F465;</div><div style={{fontSize:15,fontWeight:600,color:t.textSecondary}}>{T('noLeads')}</div></div>:
<div style={{display:'grid',gridTemplateColumns:'repeat(auto-fill, minmax(310px, 1fr))',gap:16}}>{leads.map(ld=>(<div key={ld.id}style={{background:t.card,border:`1px solid ${t.border}`,borderRadius:14,padding:20,display:'flex',flexDirection:'column',boxShadow:t.shadow,transition:'all .15s'}}onMouseEnter={e=>e.currentTarget.style.boxShadow=t.shadowMd}onMouseLeave={e=>e.currentTarget.style.boxShadow=t.shadow}>
<div style={{display:'flex',justifyContent:'space-between',alignItems:'flex-start',marginBottom:12}}><div><div style={{fontSize:15,fontWeight:600,color:t.text}}>{ld.name}</div><div style={{fontSize:12,color:t.textMuted,display:'flex',alignItems:'center',gap:4,marginTop:2}}><Phone size={10}/>{ld.phone}</div>{ld.email&&<div style={{fontSize:12,color:t.textMuted,display:'flex',alignItems:'center',gap:4,marginTop:2}}><Mail size={10}/>{ld.email}</div>}</div>
<span style={BD(ld.status==='qualified'?t.teal:ld.status==='contacted'?t.blue:ld.status==='lost'?t.red:t.textMuted)}>{T(ld.status)}</span></div>
<div style={{display:'flex',alignItems:'baseline',gap:4,marginBottom:8}}><span style={{fontSize:24,fontWeight:700,color:sc2(ld.score)}}>{ld.score}</span><span style={{fontSize:11,color:t.textMuted}}>{T('score')}</span></div>
{ld.interest&&<div style={{fontSize:12,color:t.textSecondary,marginBottom:4}}>{ld.interest}</div>}
{ld.notes&&<div style={{fontSize:12,color:t.textMuted,marginBottom:8,overflow:'hidden',textOverflow:'ellipsis',whiteSpace:'nowrap'}}>{ld.notes}</div>}
{ld.follow_up_date&&<div style={{fontSize:12,color:t.amber,display:'flex',alignItems:'center',gap:4,marginBottom:8}}><Calendar size={10}/>{T('followUp')}:{new Date(ld.follow_up_date).toLocaleDateString('en-US',{month:'short',day:'numeric'})}</div>}
<div style={{display:'flex',gap:8,marginTop:'auto',paddingTop:12,borderTop:`1px solid ${t.border}`}}><button onClick={()=>oe(ld)}style={{flex:1,padding:7,borderRadius:8,background:t.pinkBg,border:`1px solid ${t.pinkBorder}`,color:t.pink,fontSize:12,cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center',gap:4}}><Edit3 size={11}/>{T('edit')}</button><button onClick={()=>dl(ld.id)}style={{flex:1,padding:7,borderRadius:8,background:t.btnGhostBg,border:`1px solid ${t.btnGhostBorder}`,color:t.red,fontSize:12,cursor:'pointer',display:'flex',alignItems:'center',justifyContent:'center',gap:4}}><Trash2 size={11}/>{T('delete')}</button></div></div>))}</div>}
</div>)}